// StealthHumanizer - Synonym Dictionary (500+ entries)
// Each entry maps a word to an array of synonyms

export const SYNONYMS: Record<string, string[]> = {
  // A
  'abandon': ['leave', 'give up', 'forsake', 'ditch', 'walk away from'],
  'ability': ['capability', 'skill', 'capacity', 'talent', 'knack'],
  'able': ['capable', 'competent', 'qualified', 'equipped', 'fit'],
  'about': ['regarding', 'concerning', 'on the subject of', 'in relation to'],
  'above': ['over', 'higher than', 'beyond', 'atop'],
  'absence': ['lack', 'shortage', 'void', 'nonexistence'],
  'absolutely': ['completely', 'totally', 'entirely', 'utterly', 'definitely'],
  'absorb': ['soak up', 'take in', 'assimilate', 'digest', 'swallow'],
  'abstract': ['theoretical', 'conceptual', 'intangible', 'vague'],
  'abundant': ['plentiful', 'copious', 'ample', 'rich', 'generous'],
  'accept': ['acknowledge', 'embrace', 'adopt', 'take on', 'welcome'],
  'access': ['entry', 'approach', 'admission', 'way in'],
  'accident': ['mishap', 'incident', 'mishappenstance', 'fluke'],
  'accomplish': ['achieve', 'pull off', 'pull together', 'get done', 'bring about'],
  'according': ['as stated by', 'per', 'based on', 'in line with'],
  'accumulate': ['gather', 'collect', 'amass', 'build up', 'pile up'],
  'accurate': ['correct', 'precise', 'exact', 'spot-on', 'on the money'],
  'achieve': ['accomplish', 'reach', 'attain', 'pull off', 'realize'],
  'acknowledge': ['recognize', 'admit', 'accept', 'own up to', 'concede'],
  'acquire': ['get', 'obtain', 'gain', 'pick up', 'land'],
  'actually': ['in fact', 'really', 'truthfully', 'honestly', 'as it turns out'],
  'address': ['tackle', 'deal with', 'handle', 'approach', 'take on'],
  'adequate': ['sufficient', 'enough', 'passable', 'decent', 'acceptable'],
  'adjust': ['tweak', 'modify', 'adapt', 'fine-tune', 'alter'],
  'administration': ['management', 'leadership', 'the people running things'],
  'admire': ['respect', 'look up to', 'appreciate', 'esteem'],
  'adopt': ['take on', 'embrace', 'choose', 'go with', 'pick up'],
  'advance': ['progress', 'move forward', 'develop', 'push ahead'],
  'advantage': ['benefit', 'edge', 'upper hand', 'plus', 'strength'],
  'advice': ['guidance', 'counsel', 'input', 'recommendation', 'two cents'],
  'advocate': ['supporter', 'champion', 'backer', 'promoter'],
  'affect': ['influence', 'impact', 'shape', 'sway', 'alter'],
  'afford': ['have the means for', 'be able to swing', 'manage'],
  'afraid': ['scared', 'fearful', 'terrified', 'worried', 'anxious'],
  'after': ['following', 'post', 'once', 'in the wake of'],
  'afterwards': ['later', 'subsequently', 'then', 'after that'],
  'against': ['opposed to', 'resisting', 'anti'],
  'age': ['era', 'period', 'time', 'epoch'],
  'agreement': ['deal', 'pact', 'understanding', 'arrangement'],
  'almost': ['nearly', 'practically', 'virtually', 'pretty much', 'close to'],
  'alone': ['by itself', 'solo', 'on its own', 'unaccompanied'],
  'already': ['previously', 'by now', 'in advance'],
  'also': ['too', 'additionally', 'as well', 'on top of that', 'plus'],
  'although': ['even though', 'though', 'while', 'despite the fact that'],
  'always': ['constantly', 'consistently', 'perpetually', 'forever', 'nonstop'],
  'amazing': ['incredible', 'remarkable', 'stunning', 'unbelievable', 'mind-blowing'],
  'amount': ['quantity', 'number', 'volume', 'sum'],
  'analyze': ['examine', 'study', 'break down', 'look into', 'dig into'],
  'ancient': ['old', 'historic', 'age-old', 'primordial', 'from way back'],
  'angry': ['mad', 'furious', 'upset', 'livid', 'pissed off'],
  'announce': ['declare', 'reveal', 'share', 'make known', 'put out there'],
  'annoying': ['irritating', 'frustrating', 'bothersome', 'aggravating'],
  'answer': ['response', 'reply', 'solution'],
  'anxious': ['worried', 'nervous', 'uneasy', 'on edge', 'stressed'],
  'apparent': ['obvious', 'clear', 'evident', 'plain to see', 'glaring'],
  'apparently': ['seemingly', 'supposedly', 'it seems like', 'from the looks of it'],
  'appeal': ['attraction', 'draw', 'pull', 'charm'],
  'appear': ['seem', 'look like', 'come across as', 'show up'],
  'application': ['use', 'implementation', 'deployment', 'practical use'],
  'approach': ['method', 'way', 'strategy', 'tactic', 'angle'],
  'appropriate': ['suitable', 'proper', 'fitting', 'right'],
  'approve': ['endorse', 'sign off on', 'give the green light', 'back'],
  'area': ['region', 'zone', 'territory', 'space', 'field'],
  'argue': ['contend', 'claim', 'assert', 'make the case'],
  'argument': ['debate', 'dispute', 'discussion', 'case'],
  'arise': ['come up', 'emerge', 'surface', 'pop up', 'spring up'],
  'arrange': ['set up', 'organize', 'put together', 'coordinate'],
  'artificial': ['synthetic', 'man-made', 'manufactured', 'fake'],
  'aspect': ['side', 'part', 'facet', 'dimension', 'angle'],
  'assemble': ['gather', 'put together', 'bring together', 'round up'],
  'assess': ['evaluate', 'judge', 'gauge', 'measure', 'weigh up'],
  'assign': ['give', 'allocate', 'hand out', 'delegate', 'dole out'],
  'assist': ['help', 'support', 'aid', 'lend a hand'],
  'assume': ['presume', 'suppose', 'take for granted', 'figure', 'guess'],
  'assure': ['guarantee', 'promise', 'ensure', 'make certain'],
  'atmosphere': ['vibe', 'ambiance', 'feel', 'mood', 'aura'],
  'attach': ['connect', 'link', 'join', 'fasten', 'tie'],
  'attempt': ['try', 'effort', 'shot', 'stab at', 'go at'],
  'attention': ['focus', 'notice', 'awareness', 'consideration'],
  'attract': ['draw', 'pull in', 'entice', 'lure'],
  'authority': ['power', 'control', 'say-so', 'jurisdiction'],
  'available': ['accessible', 'on hand', 'at your disposal', 'free'],
  'average': ['typical', 'ordinary', 'standard', 'run-of-the-mill', 'normal'],
  'avoid': ['steer clear of', 'dodge', 'sidestep', 'shun', 'evade'],
  'awful': ['terrible', 'dreadful', 'horrible', 'atrocious'],
  // B
  'back': ['support', 'back up', 'stand behind', 'champion'],
  'basic': ['fundamental', 'core', 'essential', 'foundational'],
  'basically': ['essentially', 'fundamentally', 'at its core', 'in a nutshell'],
  'basis': ['foundation', 'base', 'grounding', 'starting point'],
  'battle': ['fight', 'struggle', 'conflict', 'clash'],
  'because': ['since', 'as', 'considering', 'given that', 'seeing as'],
  'become': ['turn into', 'grow into', 'evolve into', 'develop into'],
  'before': ['prior to', 'earlier than', 'leading up to', 'preceding'],
  'begin': ['start', 'kick off', 'get going', 'launch', 'commence'],
  'behavior': ['conduct', 'actions', 'way of acting', 'demeanor'],
  'believe': ['think', 'feel', 'reckon', 'hold the view', 'be convinced'],
  'belong': ['be part of', 'fit in', 'go with'],
  'benefit': ['advantage', 'perk', 'plus', 'upside', 'gain'],
  'besides': ['apart from', 'other than', 'in addition to', 'plus'],
  'between': ['among', 'in the middle of', 'in between'],
  'beyond': ['past', 'further than', 'outside of', 'above'],
  'big': ['large', 'huge', 'massive', 'substantial', 'major'],
  'blame': ['point the finger at', 'hold responsible', 'pin on'],
  'blend': ['mix', 'combine', 'merge', 'fuse', 'mingle'],
  'block': ['obstruct', 'prevent', 'stop', 'stand in the way of'],
  'blow': ['impact', 'hit', 'shock', 'setback'],
  'bold': ['daring', 'courageous', 'brave', 'fearless'],
  'boost': ['increase', 'lift', 'improve', 'elevate', 'bump up'],
  'boring': ['dull', 'tedious', 'uninteresting', 'dry', 'mind-numbing'],
  'bound': ['tied', 'destined', 'certain', 'headed'],
  'boundary': ['border', 'limit', 'edge', 'line'],
  'break': ['shatter', 'crack', 'fracture', 'snap', 'rupture'],
  'brief': ['short', 'quick', 'concise', 'fleeting', 'momentary'],
  'bring': ['carry', 'deliver', 'provide', 'supply'],
  'broad': ['wide', 'extensive', 'sweeping', 'far-reaching'],
  'build': ['construct', 'create', 'put together', 'develop', 'erect'],
  'burden': ['load', 'weight', 'responsibility', 'strain'],
  // C
  'calculate': ['compute', 'figure out', 'work out', 'estimate'],
  'call': ['refer to', 'label', 'name', 'describe as'],
  'capable': ['competent', 'able', 'qualified', 'equipped', 'skilled'],
  'capacity': ['ability', 'capability', 'potential', 'room'],
  'capture': ['catch', 'grab', 'record', 'seize', 'snag'],
  'careful': ['cautious', 'mindful', 'attentive', 'wary'],
  'carry': ['bring', 'transport', 'move', 'haul'],
  'case': ['instance', 'situation', 'scenario', 'example'],
  'cause': ['reason', 'root', 'source', 'driving force'],
  'cease': ['stop', 'end', 'halt', 'quit', 'discontinue'],
  'certain': ['sure', 'definite', 'specific', 'particular'],
  'challenge': ['obstacle', 'hurdle', 'test', 'difficulty', 'problem'],
  'chance': ['opportunity', 'shot', 'possibility', 'likelihood'],
  'change': ['shift', 'transform', 'alter', 'modify', 'revamp'],
  'characteristic': ['trait', 'feature', 'quality', 'attribute', 'mark'],
  'cheap': ['inexpensive', 'affordable', 'low-cost', 'budget'],
  'choose': ['pick', 'select', 'opt for', 'go with', 'settle on'],
  'circumstance': ['situation', 'condition', 'context', 'state of affairs'],
  'claim': ['assert', 'state', 'argue', 'maintain', 'contend'],
  'clear': ['obvious', 'evident', 'apparent', 'plain', 'straightforward'],
  'clearly': ['obviously', 'evidently', 'plainly', 'without a doubt'],
  'close': ['near', 'nearby', 'adjacent', 'shut'],
  'clue': ['hint', 'sign', 'indicator', 'lead', 'tip-off'],
  'collect': ['gather', 'assemble', 'accumulate', 'round up'],
  'combine': ['merge', 'join', 'blend', 'mix', 'unite'],
  'come': ['arrive', 'approach', 'show up', 'head over'],
  'common': ['widespread', 'typical', 'usual', 'standard', 'everyday'],
  'communicate': ['convey', 'express', 'get across', 'pass along', 'share'],
  'community': ['group', 'society', 'network', 'collective'],
  'company': ['business', 'firm', 'organization', 'enterprise'],
  'compare': ['contrast', 'weigh against', 'put side by side'],
  'compel': ['force', 'push', 'drive', 'pressure'],
  'compensate': ['make up for', 'offset', 'balance out', 'reimburse'],
  'compete': ['vie', 'contend', 'go head-to-head', 'battle'],
  'complain': ['grumble', 'gripe', 'whine', 'protest'],
  'complex': ['complicated', 'intricate', 'involved', 'tricky'],
  'component': ['part', 'piece', 'element', 'building block'],
  'comprehend': ['understand', 'grasp', 'wrap your head around', 'get'],
  'comprehensive': ['thorough', 'complete', 'all-inclusive', 'exhaustive'],
  'concentrate': ['focus', 'zero in on', 'hone in on', 'pay attention to'],
  'concern': ['worry', 'care', 'interest', 'issue'],
  'conclude': ['wrap up', 'finish', 'end', 'close', 'wind down'],
  'concrete': ['specific', 'solid', 'tangible', 'definite'],
  'condition': ['state', 'situation', 'shape', 'status'],
  'conduct': ['carry out', 'perform', 'execute', 'do', 'run'],
  'confirm': ['verify', 'validate', 'double-check', 'corroborate'],
  'conflict': ['clash', 'dispute', 'disagreement', 'friction', 'tension'],
  'confront': ['face', 'tackle', 'deal with', 'address head-on'],
  'confuse': ['bewilder', 'perplex', 'muddle', 'mix up'],
  'connect': ['link', 'tie', 'join', 'bridge', 'hook up'],
  'consequence': ['result', 'outcome', 'effect', 'impact', 'ramification'],
  'consider': ['think about', 'weigh', 'ponder', 'mull over', 'take into account'],
  'consist': ['be made up of', 'be composed of', 'comprise'],
  'constant': ['steady', 'continuous', 'unrelenting', 'nonstop', 'never-ending'],
  'constitute': ['make up', 'form', 'comprise', 'represent'],
  'construct': ['build', 'create', 'put together', 'erect'],
  'consult': ['ask', 'seek advice from', 'check with', 'run by'],
  'consume': ['use up', 'eat up', 'devour', 'take in'],
  'contact': ['reach out to', 'get in touch with', 'connect with'],
  'contain': ['hold', 'include', 'house', 'carry'],
  'contemporary': ['current', 'modern', 'present-day', 'today\'s'],
  'content': ['happy', 'satisfied', 'pleased', 'fine with'],
  'context': ['setting', 'background', 'circumstances', 'frame'],
  'continue': ['keep going', 'carry on', 'press on', 'persist'],
  'contract': ['agreement', 'deal', 'arrangement'],
  'contradict': ['disagree with', 'conflict with', 'go against', 'counter'],
  'contrast': ['difference', 'distinction', 'opposition', 'juxtaposition'],
  'contribute': ['chip in', 'pitch in', 'add', 'provide', 'give'],
  'control': ['manage', 'direct', 'govern', 'oversee', 'run'],
  'convenient': ['handy', 'easy', 'practical', 'accessible'],
  'convince': ['persuade', 'win over', 'talk into', 'sell on'],
  'cooperate': ['work together', 'collaborate', 'team up', 'join forces'],
  'copy': ['replica', 'duplicate', 'version', 'reproduction'],
  'core': ['heart', 'center', 'essence', 'foundation'],
  'correct': ['right', 'accurate', 'true', 'proper', 'on point'],
  'correspond': ['match', 'align', 'line up with', 'relate to'],
  'cost': ['price', 'expense', 'fee', 'charge'],
  'could': ['might', 'may', 'would be able to'],
  'count': ['matter', 'make a difference', 'carry weight'],
  'couple': ['few', 'pair', 'two or three', 'handful'],
  'course': ['path', 'route', 'direction', 'track'],
  'create': ['make', 'build', 'develop', 'craft', 'produce'],
  'creative': ['inventive', 'innovative', 'original', 'imaginative'],
  'crucial': ['critical', 'vital', 'key', 'essential', 'make-or-break'],
  'crush': ['overwhelm', 'defeat', 'destroy', 'obliterate'],
  'curious': ['intrigued', 'inquisitive', 'fascinated', 'wondering'],
  'current': ['present', 'existing', 'ongoing', 'present-day'],
  'currently': ['right now', 'at the moment', 'these days', 'as of now'],
  'customary': ['usual', 'typical', 'standard', 'normal', 'routine'],
  // D
  'damage': ['harm', 'hurt', 'ruin', 'wreck'],
  'danger': ['risk', 'threat', 'hazard', 'peril'],
  'decide': ['choose', 'determine', 'resolve', 'settle on', 'make up your mind'],
  'decision': ['choice', 'call', 'ruling', 'judgment', 'determination'],
  'declare': ['announce', 'state', 'proclaim', 'make known'],
  'decline': ['decrease', 'drop', 'fall', 'go down', 'shrink'],
  'decrease': ['reduction', 'drop', 'cut', 'dip', 'fall'],
  'deep': ['profound', 'intense', 'thorough', 'far-reaching'],
  'defeat': ['beat', 'overcome', 'conquer', 'triumph over'],
  'defend': ['protect', 'guard', 'shield', 'stand up for'],
  'define': ['spell out', 'lay out', 'specify', 'establish'],
  'definitely': ['absolutely', 'certainly', 'without a doubt', 'for sure'],
  'degree': ['extent', 'level', 'measure', 'amount'],
  'delay': ['postpone', 'put off', 'push back', 'defer'],
  'deliver': ['provide', 'supply', 'bring', 'hand over', 'give'],
  'demand': ['request', 'require', 'call for', 'need'],
  'demonstrate': ['show', 'prove', 'illustrate', 'display', 'reveal'],
  'deny': ['reject', 'refuse', 'dispute', 'push back on'],
  'depart': ['leave', 'go', 'head out', 'set off'],
  'depend': ['rely', 'count on', 'lean on', 'hinge on'],
  'depict': ['portray', 'show', 'represent', 'illustrate'],
  'deploy': ['roll out', 'put in place', 'implement', 'launch'],
  'describe': ['explain', 'detail', 'lay out', 'spell out', 'paint a picture of'],
  'description': ['account', 'breakdown', 'summary', 'overview'],
  'deserve': ['earn', 'warrant', 'merit', 'be worthy of'],
  'design': ['plan', 'create', 'develop', 'craft', 'lay out'],
  'desire': ['want', 'wish', 'longing', 'craving'],
  'destroy': ['ruin', 'wreck', 'demolish', 'obliterate', 'wipe out'],
  'detail': ['specifics', 'particulars', 'nuances', 'ins and outs'],
  'detect': ['spot', 'notice', 'identify', 'catch', 'pick up on'],
  'determine': ['figure out', 'decide', 'establish', 'pin down', 'work out'],
  'develop': ['build', 'create', 'grow', 'evolve', 'craft'],
  'device': ['tool', 'gadget', 'instrument', 'piece of equipment'],
  'devote': ['dedicate', 'commit', 'pour into', 'invest'],
  'different': ['distinct', 'various', 'diverse', 'unlike', 'separate'],
  'difficult': ['hard', 'tough', 'challenging', 'tricky', 'demanding'],
  'difficulty': ['struggle', 'challenge', 'problem', 'obstacle', 'hurdle'],
  'direct': ['straight', 'immediate', 'explicit', 'point-blank'],
  'direction': ['way', 'path', 'course', 'route'],
  'directly': ['straight', 'personally', 'face-to-face'],
  'disappear': ['vanish', 'fade', 'go away', 'dissolve'],
  'discover': ['find', 'uncover', 'stumble upon', 'come across'],
  'discuss': ['talk about', 'cover', 'explore', 'dive into', 'go over'],
  'discussion': ['conversation', 'talk', 'dialogue', 'exchange'],
  'disease': ['illness', 'sickness', 'condition', 'ailment'],
  'display': ['show', 'exhibit', 'reveal', 'present', 'put on display'],
  'distance': ['gap', 'space', 'span', 'stretch'],
  'distinct': ['clear', 'separate', 'different', 'noticeable'],
  'distribute': ['spread', 'share', 'hand out', 'disperse'],
  'disturb': ['bother', 'upset', 'interrupt', 'disrupt'],
  'diverse': ['varied', 'mixed', 'assorted', 'wide-ranging'],
  'divide': ['split', 'separate', 'break up', 'carve up'],
  'domestic': ['home', 'local', 'national', 'internal'],
  'dominant': ['leading', 'main', 'primary', 'top', 'foremost'],
  'doubt': ['question', 'uncertainty', 'skepticism', 'hesitation'],
  'downside': ['drawback', 'negative', 'catch', 'disadvantage'],
  'dramatic': ['striking', 'significant', 'major', 'noticeable', 'huge'],
  'drastic': ['extreme', 'severe', 'radical', 'harsh'],
  'duration': ['length', 'time', 'span', 'period'],
  'during': ['throughout', 'in the course of', 'while', 'over'],
  // E
  'early': ['ahead of time', 'before expected', 'at the start'],
  'earn': ['make', 'gain', 'bring in', 'pick up'],
  'ease': ['comfort', 'simplicity', 'effortlessness'],
  'economic': ['financial', 'fiscal', 'monetary'],
  'economy': ['market', 'financial system', 'economics'],
  'effect': ['impact', 'result', 'outcome', 'consequence'],
  'effective': ['successful', 'potent', 'powerful', 'efficient', 'productive'],
  'efficiency': ['productivity', 'effectiveness', 'performance'],
  'effort': ['attempt', 'try', 'push', 'energy'],
  'either': ['one or the other', 'both options', 'whichever'],
  'elaborate': ['expand on', 'detail', 'flesh out', 'go into more depth'],
  'element': ['part', 'piece', 'component', 'aspect', 'factor'],
  'eliminate': ['remove', 'get rid of', 'wipe out', 'eradicate', 'cut out'],
  'embrace': ['adopt', 'welcome', 'take on', 'accept'],
  'emerge': ['come up', 'appear', 'surface', 'arise'],
  'emphasize': ['stress', 'highlight', 'underline', 'drive home', 'accentuate'],
  'employ': ['use', 'utilize', 'apply', 'put to work'],
  'enable': ['allow', 'make possible', 'facilitate', 'let'],
  'encounter': ['come across', 'face', 'run into', 'meet'],
  'encourage': ['motivate', 'inspire', 'push', 'urge'],
  'end': ['conclusion', 'finish', 'wrap-up', 'close'],
  'enemy': ['opponent', 'adversary', 'foe', 'rival'],
  'energy': ['vigor', 'power', 'drive', 'stamina'],
  'engage': ['involve', 'participate', 'take part', 'dive in'],
  'enhance': ['improve', 'boost', 'elevate', 'upgrade', 'step up'],
  'enormous': ['huge', 'massive', 'vast', 'gigantic', 'immense'],
  'ensure': ['make sure', 'guarantee', 'see to it', 'confirm'],
  'enter': ['go into', 'join', 'step into', 'access'],
  'entire': ['whole', 'complete', 'full', 'total', 'entire'],
  'environment': ['surroundings', 'setting', 'context', 'habitat'],
  'episode': ['instance', 'occurrence', 'event', 'incident'],
  'equal': ['same', 'equivalent', 'matching', 'comparable'],
  'equip': ['provide', 'supply', 'outfit', 'arm'],
  'error': ['mistake', 'slip-up', 'blunder', 'oversight'],
  'escape': ['get away', 'flee', 'break free', 'bolt'],
  'especially': ['particularly', 'notably', 'above all', 'specifically'],
  'essential': ['crucial', 'vital', 'key', 'necessary', 'must-have'],
  'establish': ['set up', 'create', 'found', 'put in place', 'build'],
  'evaluate': ['assess', 'judge', 'measure', 'rate', 'weigh'],
  'event': ['happening', 'occasion', 'incident', 'occurrence'],
  'eventually': ['finally', 'in the end', 'sooner or later', 'down the road'],
  'every': ['each', 'all', 'every single'],
  'evidence': ['proof', 'data', 'signs', 'indication', 'findings'],
  'evil': ['bad', 'wicked', 'terrible', 'malicious'],
  'exact': ['precise', 'accurate', 'specific', 'spot-on'],
  'examine': ['inspect', 'look at', 'analyze', 'review', 'check out'],
  'example': ['instance', 'case', 'illustration', 'sample'],
  'excellent': ['outstanding', 'great', 'superb', 'top-notch', 'stellar'],
  'except': ['other than', 'apart from', 'besides', 'but'],
  'exchange': ['swap', 'trade', 'switch', 'give and take'],
  'exciting': ['thrilling', 'stirring', 'electrifying', 'pulse-pounding'],
  'exclude': ['leave out', 'omit', 'rule out', 'keep out'],
  'execute': ['carry out', 'perform', 'do', 'implement'],
  'exhibit': ['show', 'display', 'present', 'demonstrate'],
  'exist': ['be present', 'live', 'occur', 'be around'],
  'expand': ['grow', 'broaden', 'scale up', 'extend', 'stretch'],
  'expect': ['anticipate', 'foresee', 'look forward to', 'predict'],
  'expense': ['cost', 'price', 'charge', 'outlay'],
  'experience': ['go through', 'face', 'live through', 'encounter'],
  'experiment': ['test', 'trial', 'tryout', 'pilot'],
  'expert': ['specialist', 'pro', 'authority', 'master'],
  'explain': ['clarify', 'spell out', 'break down', 'walk through'],
  'explicit': ['clear', 'direct', 'specific', 'stated'],
  'explore': ['investigate', 'look into', 'dive into', 'probe', 'dig into'],
  'expose': ['reveal', 'uncover', 'show', 'bring to light'],
  'extend': ['stretch', 'expand', 'lengthen', 'reach'],
  'extent': ['degree', 'scope', 'measure', 'level'],
  'external': ['outside', 'outer', 'foreign'],
  'extra': ['additional', 'more', 'bonus', 'supplementary'],
  'extreme': ['intense', 'severe', 'drastic', 'radical'],
  // F
  'face': ['confront', 'deal with', 'tackle', 'take on'],
  'fact': ['reality', 'truth', 'reality of the matter'],
  'factor': ['element', 'variable', 'piece', 'consideration'],
  'fail': ['fall short', 'not make it', 'come up short', 'fall flat'],
  'failure': ['flop', 'disaster', 'setback', 'letdown'],
  'fair': ['reasonable', 'just', 'balanced', 'equitable'],
  'faith': ['belief', 'trust', 'confidence'],
  'familiar': ['known', 'recognized', 'well-known', 'comfortable'],
  'famous': ['well-known', 'renowned', 'celebrated', 'notable'],
  'feature': ['characteristic', 'aspect', 'quality', 'element'],
  'few': ['a handful of', 'a couple of', 'not many', 'several'],
  'fierce': ['intense', 'aggressive', 'strong', 'powerful'],
  'figure': ['number', 'stat', 'amount', 'quantity'],
  'finally': ['at last', 'in the end', 'at long last', 'after all that'],
  'financial': ['monetary', 'economic', 'money-related', 'fiscal'],
  'finding': ['discovery', 'result', 'conclusion', 'observation'],
  'firm': ['company', 'business', 'organization', 'enterprise'],
  'flexible': ['adaptable', 'versatile', 'adjustable', 'moldable'],
  'flow': ['movement', 'stream', 'current', 'progression'],
  'focus': ['center', 'concentrate', 'zero in', 'hone in on'],
  'follow': ['go after', 'track', 'pursue', 'trail'],
  'force': ['power', 'strength', 'pressure', 'might'],
  'foreign': ['external', 'outside', 'international', 'alien'],
  'form': ['shape', 'structure', 'type', 'format'],
  'formal': ['official', 'proper', 'structured', 'ceremonial'],
  'former': ['previous', 'past', 'earlier', 'old'],
  'formula': ['recipe', 'approach', 'method', 'blueprint'],
  'fortune': ['wealth', 'money', 'riches', 'prosperity'],
  'forward': ['ahead', 'onward', 'on', 'in front'],
  'foundation': ['base', 'basis', 'grounding', 'cornerstone'],
  'fraction': ['portion', 'part', 'piece', 'sliver'],
  'fragment': ['piece', 'bit', 'chunk', 'shard', 'segment'],
  'framework': ['structure', 'system', 'setup', 'skeleton'],
  'frequent': ['common', 'regular', 'often', 'routine'],
  'fresh': ['new', 'novel', 'original', 'recent'],
  'friend': ['buddy', 'pal', 'mate', 'companion'],
  'front': ['front line', 'forefront', 'lead'],
  'fulfill': ['meet', 'satisfy', 'accomplish', 'deliver on'],
  'function': ['purpose', 'role', 'job', 'use'],
  'fundamental': ['basic', 'core', 'essential', 'foundational', 'central'],
  'future': ['what lies ahead', 'down the road', 'tomorrow'],
  // G
  'gain': ['acquire', 'obtain', 'earn', 'pick up', 'secure'],
  'gathering': ['collection', 'assembly', 'meetup', 'get-together'],
  'general': ['overall', 'broad', 'widespread', 'common'],
  'generate': ['create', 'produce', 'make', 'yield', 'spawn'],
  'generous': ['giving', 'kind', 'lavish', 'big-hearted'],
  'genuine': ['real', 'authentic', 'sincere', 'true', 'legit'],
  'goal': ['aim', 'objective', 'target', 'endgame', 'purpose'],
  'good': ['solid', 'great', 'strong', 'quality', 'decent'],
  'gradual': ['slow', 'steady', 'progressive', 'incremental'],
  'grand': ['big', 'major', 'impressive', 'ambitious'],
  'grant': ['give', 'award', 'provide', 'hand over'],
  'grasp': ['understand', 'comprehend', 'get', 'wrap your head around'],
  'great': ['huge', 'significant', 'major', 'massive', 'notable'],
  'ground': ['basis', 'foundation', 'reasoning', 'rationale'],
  'group': ['bunch', 'collection', 'cluster', 'team'],
  'grow': ['expand', 'increase', 'develop', 'build up'],
  'guarantee': ['promise', 'ensure', 'warrant', 'certify'],
  'guard': ['protect', 'defend', 'watch over', 'shield'],
  'guidance': ['direction', 'advice', 'help', 'support', 'leadership'],
  // H
  'handle': ['deal with', 'manage', 'tackle', 'address', 'take care of'],
  'happen': ['occur', 'take place', 'come about', 'go down'],
  'harsh': ['severe', 'tough', 'strict', 'rough', 'brutal'],
  'hazard': ['danger', 'risk', 'threat', 'peril'],
  'head': ['lead', 'be in charge of', 'run', 'direct'],
  'healthy': ['wholesome', 'nutritious', 'fit', 'well'],
  'heavy': ['weighty', 'substantial', 'serious', 'intense'],
  'help': ['assist', 'support', 'aid', 'lend a hand'],
  'hidden': ['concealed', 'buried', 'tucked away', 'obscured'],
  'highlight': ['emphasize', 'stress', 'point out', 'spotlight', 'call attention to'],
  'hint': ['clue', 'sign', 'suggestion', 'tip', 'trace'],
  'hold': ['keep', 'maintain', 'retain', 'carry'],
  'honest': ['truthful', 'sincere', 'straightforward', 'candid'],
  'hope': ['wish', 'expect', 'look forward to', 'aim for'],
  'horrible': ['terrible', 'awful', 'dreadful', 'atrocious'],
  'huge': ['massive', 'enormous', 'giant', 'immense', 'colossal'],
  'human': ['person', 'individual', 'people'],
  'humor': ['comedy', 'funny side', 'amusement', 'wit'],
  'hurt': ['harm', 'injure', 'damage', 'wound'],
  // I
  'idea': ['concept', 'thought', 'notion', 'plan', 'vision'],
  'ideal': ['perfect', 'optimal', 'best possible', 'model'],
  'identify': ['spot', 'recognize', 'pinpoint', 'detect', 'name'],
  'ignore': ['disregard', 'overlook', 'brush off', 'pay no attention to'],
  'illustrate': ['show', 'demonstrate', 'exemplify', 'depict'],
  'impact': ['effect', 'influence', 'consequence', 'repercussion'],
  'implement': ['put in place', 'carry out', 'roll out', 'execute', 'deploy'],
  'imply': ['suggest', 'hint at', 'indicate', 'insinuate'],
  'importance': ['significance', 'weight', 'relevance', 'priority'],
  'important': ['crucial', 'key', 'vital', 'significant', 'essential'],
  'impose': ['force', 'apply', 'place', 'inflict'],
  'improve': ['enhance', 'boost', 'upgrade', 'better', 'step up'],
  'incident': ['event', 'occurrence', 'episode', 'happening'],
  'include': ['feature', 'contain', 'incorporate', 'cover', 'involve'],
  'increase': ['rise', 'grow', 'go up', 'climb', 'surge'],
  'incredible': ['amazing', 'unbelievable', 'remarkable', 'extraordinary'],
  'indeed': ['absolutely', 'truly', 'without question', 'certainly'],
  'independent': ['autonomous', 'self-sufficient', 'standalone'],
  'indicate': ['show', 'suggest', 'point to', 'signal', 'reveal'],
  'individual': ['person', 'single', 'specific', 'unique'],
  'inevitable': ['unavoidable', 'certain', 'bound to happen', 'guaranteed'],
  'influence': ['impact', 'effect', 'sway', 'shape', 'steer'],
  'inform': ['tell', 'let know', 'notify', 'update', 'give a heads-up'],
  'initial': ['first', 'starting', 'opening', 'early'],
  'innovation': ['breakthrough', 'new idea', 'advance', 'novelty'],
  'input': ['contribution', 'feedback', 'thoughts', 'perspective'],
  'insight': ['understanding', 'revelation', 'realization', 'perspective'],
  'inspect': ['examine', 'check', 'review', 'look over'],
  'install': ['set up', 'put in', 'configure'],
  'instance': ['example', 'case', 'occasion', 'situation'],
  'instead': ['rather', 'alternatively', 'as a substitute'],
  'integrate': ['combine', 'blend', 'weave in', 'incorporate'],
  'intend': ['plan', 'mean to', 'aim to', 'set out to'],
  'intense': ['strong', 'powerful', 'severe', 'heavy', 'fierce'],
  'interest': ['fascination', 'curiosity', 'attention', 'engagement'],
  'interesting': ['fascinating', 'intriguing', 'compelling', 'thought-provoking'],
  'internal': ['inside', 'inner', 'domestic'],
  'interpret': ['read', 'understand', 'make sense of', 'decode'],
  'interview': ['conversation', 'discussion', 'questioning', 'chat'],
  'introduce': ['bring in', 'present', 'launch', 'roll out'],
  'intuition': ['gut feeling', 'instinct', 'hunch', 'sixth sense'],
  'invade': ['enter', 'encroach', 'overrun', 'infiltrate'],
  'invest': ['put money into', 'fund', 'back', 'sink resources into'],
  'investigate': ['look into', 'examine', 'probe', 'dig into', 'explore'],
  'involve': ['include', 'engage', 'draw in', 'require'],
  'issue': ['problem', 'matter', 'concern', 'topic', 'question'],
  'item': ['thing', 'piece', 'object', 'unit'],
  // J
  'job': ['task', 'role', 'position', 'gig', 'work'],
  'join': ['connect', 'link', 'unite', 'combine', 'team up'],
  'journal': ['diary', 'log', 'record', 'publication'],
  'journey': ['trip', 'voyage', 'expedition', 'adventure', 'trek'],
  'judge': ['evaluate', 'assess', 'rate', 'determine'],
  'just': ['simply', 'merely', 'only', 'purely'],
  // K
  'keep': ['maintain', 'hold on to', 'retain', 'preserve'],
  'key': ['crucial', 'vital', 'essential', 'central', 'main'],
  'kind': ['type', 'sort', 'variety', 'category', 'flavor'],
  'knowledge': ['understanding', 'expertise', 'know-how', 'insight'],
  // L
  'lack': ['shortage', 'absence', 'deficiency', 'dearth'],
  'landscape': ['scene', 'terrain', 'environment', 'picture'],
  'large': ['big', 'huge', 'substantial', 'sizeable', 'massive'],
  'last': ['final', 'ultimate', 'closing', 'concluding'],
  'late': ['tardy', 'delayed', 'behind schedule'],
  'latter': ['second', 'last-mentioned', 'later one'],
  'launch': ['start', 'kick off', 'roll out', 'introduce', 'debut'],
  'law': ['rule', 'regulation', 'statute', 'legislation'],
  'lead': ['guide', 'direct', 'steer', 'head up', 'be at the front of'],
  'learn': ['find out', 'discover', 'pick up', 'figure out'],
  'least': ['minimum', 'smallest amount', 'bare minimum'],
  'leave': ['depart', 'go', 'exit', 'head out'],
  'legal': ['lawful', 'legitimate', 'by the book'],
  'level': ['degree', 'extent', 'amount', 'standard'],
  'likely': ['probable', 'expected', 'plausible', 'a good bet'],
  'limit': ['cap', 'boundary', 'ceiling', 'restriction', 'constraint'],
  'link': ['connection', 'tie', 'relationship', 'bond'],
  'literally': ['actually', 'truly', 'exactly', 'quite literally'],
  'little': ['small', 'tiny', 'bit', 'modest'],
  'locate': ['find', 'pinpoint', 'track down', 'discover'],
  'logical': ['rational', 'reasonable', 'sensible', 'sound'],
  'look': ['appear', 'seem', 'glimpse', 'glance'],
  'lose': ['misplace', 'drop', 'forfeit', 'be deprived of'],
  'lot': ['bunch', 'ton', 'heap', 'load', 'pile'],
  'low': ['small', 'minimal', 'down', 'below average'],
  // M
  'main': ['primary', 'chief', 'principal', 'key', 'central'],
  'maintain': ['keep', 'preserve', 'sustain', 'uphold'],
  'major': ['big', 'significant', 'important', 'notable', 'substantial'],
  'manage': ['handle', 'deal with', 'run', 'oversee'],
  'manner': ['way', 'method', 'approach', 'style', 'fashion'],
  'many': ['a lot of', 'tons of', 'numerous', 'quite a few', 'a bunch of'],
  'market': ['industry', 'sector', 'business', 'economy'],
  'massive': ['huge', 'enormous', 'gigantic', 'immense'],
  'material': ['substance', 'stuff', 'content', 'matter'],
  'matter': ['issue', 'subject', 'topic', 'concern'],
  'maximum': ['highest', 'greatest', 'top', 'peak'],
  'mean': ['signify', 'indicate', 'represent', 'imply'],
  'measure': ['gauge', 'assess', 'evaluate', 'quantify'],
  'method': ['approach', 'technique', 'way', 'strategy', 'process'],
  'might': ['may', 'could', 'perhaps', 'possibly'],
  'million': ['a whole lot', 'countless', 'a massive amount'],
  'mind': ['brain', 'head', 'thoughts', 'thinking'],
  'minimum': ['least', 'lowest', 'bare minimum', 'baseline'],
  'minor': ['small', 'slight', 'trivial', 'insignificant'],
  'minute': ['tiny', 'minuscule', 'microscopic', 'tiny little'],
  'mistake': ['error', 'slip-up', 'blunder', 'oversight', 'mess-up'],
  'model': ['framework', 'example', 'pattern', 'template'],
  'modern': ['current', 'contemporary', 'present-day', 'up-to-date'],
  'modify': ['change', 'adjust', 'alter', 'tweak', 'revise'],
  'moment': ['point', 'instance', 'time', 'juncture'],
  'money': ['cash', 'funds', 'capital', 'resources'],
  'monitor': ['watch', 'track', 'keep an eye on', 'observe'],
  'mood': ['feeling', 'state of mind', 'vibe', 'temperament'],
  'moral': ['ethical', 'right', 'principled'],
  'motivation': ['drive', 'incentive', 'reason', 'push'],
  'motion': ['movement', 'action', 'gesture'],
  'mount': ['increase', 'rise', 'grow', 'build up'],
  'move': ['shift', 'transition', 'relocate', 'budge'],
  'multiple': ['several', 'various', 'numerous', 'a number of'],
  'mutual': ['shared', 'common', 'joint', 'reciprocal'],
  // N
  'narrow': ['tight', 'slim', 'limited', 'restricted'],
  'nation': ['country', 'state', 'land'],
  'natural': ['normal', 'organic', 'innate', 'inherent'],
  'necessary': ['needed', 'required', 'essential', 'must-have'],
  'negative': ['bad', 'unfavorable', 'downside', 'pessimistic'],
  'neglect': ['ignore', 'overlook', 'forget about', 'brush off'],
  'network': ['web', 'system', 'grid', 'connections'],
  'neutral': ['impartial', 'unbiased', 'objective', 'middle-ground'],
  'nevertheless': ['however', 'still', 'nonetheless', 'even so'],
  'next': ['following', 'upcoming', 'coming'],
  'nice': ['good', 'pleasant', 'great', 'lovely', 'fine'],
  'normal': ['typical', 'standard', 'usual', 'regular', 'average'],
  'notable': ['significant', 'remarkable', 'worth mentioning', 'noteworthy'],
  'notion': ['idea', 'concept', 'belief', 'thought'],
  'novel': ['new', 'original', 'fresh', 'innovative'],
  'nowadays': ['these days', 'today', 'currently', 'in this day and age'],
  'numerous': ['many', 'several', 'a lot of', 'tons of', 'countless'],
  // O
  'obvious': ['clear', 'apparent', 'evident', 'plain to see'],
  'obtain': ['get', 'acquire', 'secure', 'gain', 'pick up'],
  'occasion': ['event', 'instance', 'moment', 'time'],
  'occupy': ['take up', 'fill', 'hold', 'use'],
  'occur': ['happen', 'take place', 'come about', 'arise'],
  'odd': ['strange', 'weird', 'unusual', 'peculiar'],
  'offer': ['provide', 'give', 'present', 'put forward'],
  'official': ['formal', 'authorized', 'approved'],
  'often': ['frequently', 'regularly', 'a lot', 'commonly'],
  'ongoing': ['continuing', 'active', 'current', 'in progress'],
  'opinion': ['view', 'perspective', 'take', 'stance', 'position'],
  'opponent': ['rival', 'competitor', 'adversary', 'challenger'],
  'opportunity': ['chance', 'opening', 'shot', 'possibility'],
  'oppose': ['resist', 'fight against', 'object to', 'push back on'],
  'option': ['choice', 'alternative', 'possibility'],
  'order': ['arrangement', 'sequence', 'organization', 'structure'],
  'ordinary': ['normal', 'average', 'typical', 'standard', 'regular'],
  'organize': ['arrange', 'set up', 'structure', 'put together', 'coordinate'],
  'origin': ['source', 'root', 'beginning', 'starting point'],
  'original': ['initial', 'first', 'authentic', 'genuine'],
  'outcome': ['result', 'consequence', 'effect', 'end result'],
  'overcome': ['beat', 'conquer', 'defeat', 'get past', 'surmount'],
  'overlap': ['intersect', 'coincide', 'run parallel'],
  'overlook': ['miss', 'ignore', 'disregard', 'skip over'],
  'owe': ['be indebted to', 'be in debt to'],
  'own': ['personal', 'individual', 'possess'],
  // P
  'pace': ['speed', 'rate', 'tempo', 'rhythm'],
  'part': ['piece', 'section', 'portion', 'component'],
  'participate': ['take part', 'join in', 'get involved', 'engage'],
  'particular': ['specific', 'certain', 'exact', 'given'],
  'partner': ['ally', 'collaborator', 'teammate', 'associate'],
  'pass': ['go by', 'come to an end', 'wrap up'],
  'pattern': ['trend', 'tendency', 'model', 'theme'],
  'pause': ['stop briefly', 'hesitate', 'take a break'],
  'pay': ['compensate', 'reimburse', 'settle', 'fork over'],
  'peak': ['top', 'summit', 'highest point', 'crest'],
  'penalty': ['punishment', 'fine', 'cost', 'consequence'],
  'perceive': ['see', 'notice', 'observe', 'interpret'],
  'percent': ['percentage', 'portion', 'share', 'proportion'],
  'perform': ['do', 'carry out', 'execute', 'deliver'],
  'period': ['time', 'era', 'span', 'stretch'],
  'permit': ['allow', 'let', 'authorize', 'give the green light'],
  'persist': ['keep going', 'continue', 'hang in there', 'stick with it'],
  'perspective': ['viewpoint', 'angle', 'standpoint', 'point of view', 'lens'],
  'phrase': ['expression', 'saying', 'wording', 'term'],
  'physical': ['bodily', 'material', 'tangible', 'concrete'],
  'pick': ['choose', 'select', 'opt for', 'go with'],
  'piece': ['part', 'segment', 'bit', 'chunk', 'section'],
  'place': ['spot', 'location', 'area', 'position', 'site'],
  'plan': ['strategy', 'scheme', 'blueprint', 'proposal', 'roadmap'],
  'platform': ['system', 'framework', 'infrastructure', 'setup'],
  'play': ['role', 'part', 'function', 'contribute'],
  'pleasure': ['joy', 'delight', 'enjoyment', 'satisfaction'],
  'point': ['purpose', 'objective', 'goal', 'message'],
  'popular': ['well-liked', 'trending', 'in demand', 'widely used'],
  'portion': ['part', 'section', 'share', 'piece'],
  'position': ['stance', 'viewpoint', 'place', 'role', 'situation'],
  'positive': ['good', 'favorable', 'optimistic', 'encouraging'],
  'possess': ['have', 'own', 'hold', 'carry'],
  'possibility': ['chance', 'option', 'potential', 'likelihood'],
  'potential': ['possibility', 'promise', 'prospects', 'room to grow'],
  'power': ['strength', 'force', 'energy', 'authority'],
  'practical': ['useful', 'realistic', 'actionable', 'hands-on'],
  'precisely': ['exactly', 'specifically', 'spot-on', 'to the letter'],
  'predict': ['forecast', 'foresee', 'anticipate', 'project'],
  'prefer': ['favor', 'lean toward', 'opt for', 'like better'],
  'prepare': ['get ready', 'set up', 'gear up', 'prime'],
  'present': ['current', 'existing', 'show', 'display', 'offer'],
  'preserve': ['protect', 'maintain', 'save', 'keep intact'],
  'pressing': ['urgent', 'critical', 'important', 'immediate'],
  'pressure': ['stress', 'tension', 'strain', 'weight'],
  'pretend': ['fake', 'act like', 'put on', 'make believe'],
  'prevent': ['stop', 'block', 'avoid', 'ward off', 'keep from'],
  'previous': ['earlier', 'prior', 'past', 'former'],
  'primary': ['main', 'chief', 'principal', 'central', 'key'],
  'prime': ['top', 'best', 'main', 'ideal'],
  'principle': ['rule', 'belief', 'value', 'tenet', 'core idea'],
  'priority': ['top concern', 'main focus', 'first order of business'],
  'problem': ['issue', 'challenge', 'difficulty', 'headache', 'sticking point'],
  'procedure': ['process', 'method', 'steps', 'approach'],
  'proceed': ['move forward', 'continue', 'go ahead', 'advance'],
  'process': ['method', 'system', 'approach', 'procedure'],
  'produce': ['create', 'generate', 'make', 'yield', 'put out'],
  'product': ['item', 'good', 'output', 'offering'],
  'professional': ['pro', 'expert', 'specialist', 'trained'],
  'profit': ['gain', 'return', 'earnings', 'bottom line'],
  'program': ['initiative', 'project', 'plan', 'scheme'],
  'progress': ['advancement', 'development', 'headway', 'forward movement'],
  'project': ['plan', 'initiative', 'undertaking', 'effort'],
  'promise': ['guarantee', 'commitment', 'pledge', 'word'],
  'promote': ['push', 'advance', 'champion', 'advocate for'],
  'proper': ['correct', 'appropriate', 'right', 'suitable'],
  'property': ['asset', 'possession', 'feature', 'characteristic'],
  'proposal': ['plan', 'offer', 'suggestion', 'pitch'],
  'propose': ['suggest', 'put forward', 'offer', 'recommend'],
  'prospect': ['possibility', 'chance', 'outlook', 'potential'],
  'protect': ['defend', 'guard', 'shield', 'safeguard'],
  'prove': ['demonstrate', 'show', 'confirm', 'establish'],
  'provide': ['supply', 'give', 'deliver', 'offer', 'furnish'],
  'pull': ['draw', 'tug', 'drag', 'extract'],
  'purchase': ['buy', 'acquire', 'get', 'pick up'],
  'purpose': ['goal', 'aim', 'objective', 'reason', 'mission'],
  'pursue': ['chase', 'go after', 'follow', 'seek'],
  'push': ['drive', 'force', 'press', 'urge'],
  'put': ['place', 'set', 'position', 'lay down'],
  // Q
  'qualify': ['meet the criteria', 'be eligible', 'fit the bill'],
  'quality': ['standard', 'caliber', 'level', 'grade'],
  'quantity': ['amount', 'number', 'volume', 'bulk'],
  'question': ['issue', 'doubt', 'uncertainty', 'inquiry'],
  'quick': ['fast', 'rapid', 'speedy', 'swift', 'prompt'],
  'quiet': ['silent', 'still', 'calm', 'peaceful'],
  'quite': ['fairly', 'rather', 'pretty', 'somewhat'],
  // R
  'radical': ['extreme', 'drastic', 'fundamental', 'revolutionary'],
  'raise': ['lift', 'increase', 'bring up', 'elevate'],
  'range': ['scope', 'spectrum', 'span', 'variety'],
  'rapid': ['fast', 'quick', 'swift', 'speedy'],
  'rare': ['uncommon', 'scarce', 'unusual', 'hard to find'],
  'rate': ['speed', 'pace', 'frequency', 'ratio'],
  'rather': ['somewhat', 'instead', 'more like', 'preferably'],
  'reach': ['arrive at', 'get to', 'attain', 'hit'],
  'react': ['respond', 'reply', 'answer back'],
  'real': ['genuine', 'actual', 'authentic', 'true'],
  'realize': ['recognize', 'understand', 'become aware of', 'figure out'],
  'really': ['truly', 'genuinely', 'actually', 'honestly'],
  'reason': ['cause', 'motive', 'rationale', 'basis', 'why'],
  'reasonable': ['fair', 'sensible', 'logical', 'rational', 'sound'],
  'recall': ['remember', 'think back to', 'recollect', 'call to mind'],
  'receive': ['get', 'obtain', 'take in', 'accept'],
  'recent': ['latest', 'new', 'current', 'not long ago'],
  'recognize': ['acknowledge', 'identify', 'admit', 'spot'],
  'recommend': ['suggest', 'advise', 'propose', 'endorse'],
  'recover': ['bounce back', 'get back', 'regain', 'restore'],
  'reduce': ['cut', 'decrease', 'lower', 'trim', 'slash'],
  'refer': ['point to', 'mention', 'direct to', 'allude to'],
  'reflect': ['show', 'mirror', 'demonstrate', 'reveal'],
  'regular': ['routine', 'normal', 'standard', 'typical', 'usual'],
  'relate': ['connect', 'link', 'apply to', 'tie in with'],
  'release': ['put out', 'launch', 'roll out', 'unveil', 'drop'],
  'relevant': ['applicable', 'related', 'pertinent', 'on-point'],
  'reliable': ['dependable', 'trustworthy', 'consistent', 'solid'],
  'relief': ['comfort', 'ease', 'reassurance', 'break'],
  'rely': ['depend', 'count on', 'lean on', 'trust'],
  'remain': ['stay', 'keep', 'continue to be', 'linger'],
  'remark': ['comment', 'observation', 'note', 'statement'],
  'remarkable': ['notable', 'extraordinary', 'impressive', 'outstanding'],
  'remember': ['recall', 'think of', 'keep in mind', 'not forget'],
  'remind': ['prompt', 'jog someone\'s memory', 'bring up'],
  'remove': ['get rid of', 'take out', 'eliminate', 'delete', 'strip away'],
  'repeat': ['do again', 'say again', 'reiterate'],
  'replace': ['swap', 'substitute', 'exchange', 'swap out'],
  'represent': ['stand for', 'symbolize', 'embody', 'illustrate'],
  'request': ['ask', 'ask for', 'call for', 'demand'],
  'require': ['need', 'demand', 'call for', 'necessitate'],
  'research': ['study', 'investigation', 'inquiry', 'analysis'],
  'reserve': ['save', 'hold back', 'keep', 'set aside'],
  'resist': ['fight', 'withstand', 'push back against', 'hold off'],
  'resolve': ['solve', 'fix', 'settle', 'address', 'work out'],
  'resource': ['asset', 'tool', 'material', 'source'],
  'respond': ['reply', 'answer', 'react', 'get back to'],
  'responsible': ['accountable', 'in charge', 'at fault'],
  'restore': ['bring back', 'recover', 'rebuild', 'repair'],
  'restrict': ['limit', 'cap', 'constrain', 'hold back'],
  'result': ['outcome', 'consequence', 'effect', 'end product'],
  'retain': ['keep', 'hold on to', 'maintain', 'preserve'],
  'retire': ['step down', 'bow out', 'leave', 'wrap up a career'],
  'reveal': ['show', 'uncover', 'disclose', 'expose', 'bring to light'],
  'revenue': ['income', 'earnings', 'takings', 'money coming in'],
  'reverse': ['flip', 'turn around', 'undo', 'invert'],
  'review': ['evaluate', 'assess', 'look over', 'go through'],
  'revolution': ['upheaval', 'transformation', 'overhaul', 'shake-up'],
  'rich': ['wealthy', 'well-off', 'prosperous', 'loaded'],
  'rise': ['increase', 'climb', 'go up', 'surge', 'jump'],
  'risk': ['danger', 'hazard', 'threat', 'gamble', 'chance'],
  'role': ['part', 'function', 'job', 'position', 'purpose'],
  'rough': ['tough', 'difficult', 'harsh', 'coarse', 'uneven'],
  'roughly': ['about', 'approximately', 'around', 'close to'],
  'route': ['path', 'way', 'course', 'direction'],
  'rule': ['regulation', 'guideline', 'principle', 'law'],
  'rumor': ['gossip', 'talk', 'buzz', 'word on the street'],
  // S
  'safe': ['secure', 'protected', 'out of harm\'s way'],
  'satisfy': ['meet', 'fulfill', 'please', 'answer'],
  'scale': ['size', 'scope', 'extent', 'magnitude', 'level'],
  'scene': ['setting', 'location', 'situation', 'sight'],
  'scope': ['range', 'extent', 'reach', 'breadth'],
  'secure': ['safe', 'protected', 'locked down', 'stable'],
  'seek': ['look for', 'search for', 'pursue', 'go after'],
  'select': ['choose', 'pick', 'opt for', 'hand-pick'],
  'sense': ['feeling', 'understanding', 'perception', 'awareness'],
  'serious': ['significant', 'severe', 'grave', 'major', 'no joke'],
  'serve': ['function as', 'act as', 'work as'],
  'set': ['put', 'place', 'establish', 'lay out'],
  'settle': ['resolve', 'decide', 'agree on', 'work out'],
  'several': ['multiple', 'a few', 'various', 'a number of'],
  'severe': ['serious', 'intense', 'harsh', 'extreme', 'heavy'],
  'shape': ['form', 'mold', 'influence', 'define'],
  'share': ['portion', 'part', 'slice', 'piece'],
  'sharp': ['keen', 'acute', 'precise', 'quick'],
  'shift': ['change', 'move', 'transition', 'switch'],
  'short': ['brief', 'quick', 'concise', 'compact'],
  'show': ['demonstrate', 'reveal', 'display', 'present', 'point out'],
  'shut': ['close', 'seal', 'lock'],
  'significant': ['important', 'major', 'notable', 'meaningful', 'substantial'],
  'similar': ['alike', 'comparable', 'like', 'analogous'],
  'simple': ['easy', 'straightforward', 'basic', 'uncomplicated'],
  'simply': ['just', 'merely', 'only', 'basically'],
  'situation': ['scenario', 'circumstance', 'context', 'state of affairs'],
  'size': ['scale', 'magnitude', 'dimensions', 'extent'],
  'skill': ['ability', 'talent', 'expertise', 'capability'],
  'slow': ['gradual', 'unhurried', 'steady', 'leisurely'],
  'small': ['tiny', 'little', 'modest', 'minor'],
  'smart': ['clever', 'intelligent', 'sharp', 'bright', 'savvy'],
  'smooth': ['seamless', 'effortless', 'easy', 'fluid'],
  'solution': ['answer', 'fix', 'resolution', 'way forward'],
  'some': ['a few', 'several', 'a handful of', 'certain'],
  'source': ['origin', 'root', 'starting point', 'cause'],
  'specific': ['particular', 'exact', 'precise', 'given'],
  'spot': ['place', 'location', 'position', 'site'],
  'spread': ['expand', 'extend', 'distribute', 'disseminate'],
  'stable': ['steady', 'secure', 'firm', 'solid'],
  'standard': ['normal', 'typical', 'usual', 'baseline'],
  'start': ['begin', 'kick off', 'launch', 'get going'],
  'state': ['condition', 'status', 'situation', 'declare'],
  'step': ['stage', 'phase', 'move', 'action'],
  'still': ['yet', 'even so', 'nevertheless', 'nonetheless'],
  'stimulate': ['trigger', 'spark', 'encourage', 'activate'],
  'stop': ['halt', 'cease', 'end', 'quit', 'cut off'],
  'straight': ['direct', 'immediate', 'honest', 'simple'],
  'strategy': ['plan', 'approach', 'game plan', 'tactic'],
  'strength': ['power', 'advantage', 'strong point', 'muscle'],
  'strict': ['firm', 'tough', 'rigid'],
  'strike': ['hit', 'attack', 'impact', 'land on'],
  'structure': ['framework', 'organization', 'setup', 'arrangement'],
  'struggle': ['fight', 'battle', 'effort', 'grapple'],
  'study': ['research', 'examination', 'analysis', 'investigation'],
  'stuff': ['things', 'material', 'items', 'content'],
  'style': ['approach', 'manner', 'way', 'flavor'],
  'subject': ['topic', 'theme', 'matter', 'area of focus'],
  'submit': ['send in', 'hand in', 'turn in', 'deliver'],
  'subsequent': ['following', 'later', 'next', 'ensuing'],
  'substance': ['material', 'content', 'essence', 'core'],
  'substitute': ['replacement', 'alternative', 'stand-in', 'swap'],
  'succeed': ['achieve', 'accomplish', 'make it', 'pull it off'],
  'success': ['achievement', 'win', 'triumph', 'victory'],
  'sufficient': ['enough', 'adequate', 'plenty'],
  'suggest': ['propose', 'recommend', 'hint at', 'float', 'put forward'],
  'suitable': ['appropriate', 'fitting', 'right', 'proper'],
  'sum': ['total', 'amount', 'whole', 'aggregate'],
  'supply': ['provide', 'deliver', 'furnish', 'give'],
  'support': ['back', 'help', 'champion', 'stand behind'],
  'suppose': ['assume', 'guess', 'presume', 'imagine'],
  'sure': ['certain', 'confident', 'positive', 'definite'],
  'surprise': ['shock', 'unexpected', 'astonishment', 'twist'],
  'surround': ['encircle', 'envelop', 'ring', 'wrap around'],
  'survey': ['poll', 'study', 'assessment', 'overview'],
  'survive': ['make it', 'pull through', 'endure', 'last'],
  'suspect': ['think', 'believe', 'guess', 'have a hunch'],
  'sustain': ['maintain', 'support', 'keep up', 'uphold'],
  'symbol': ['sign', 'mark', 'representation', 'emblem'],
  'system': ['network', 'setup', 'framework', 'structure'],
  // T
  'tackle': ['address', 'deal with', 'handle', 'take on', 'approach'],
  'take': ['grab', 'pick up', 'claim', 'seize'],
  'tale': ['story', 'account', 'narrative', 'version'],
  'target': ['goal', 'aim', 'objective', 'mark'],
  'task': ['job', 'assignment', 'chore', 'duty', 'mission'],
  'team': ['group', 'crew', 'squad', 'unit'],
  'technique': ['method', 'approach', 'strategy', 'way'],
  'technology': ['tech', 'tools', 'systems', 'innovation'],
  'tell': ['say', 'inform', 'let know', 'reveal'],
  'tend': ['be inclined to', 'have a tendency to', 'usually'],
  'term': ['period', 'duration', 'word', 'phrase'],
  'terrible': ['awful', 'horrible', 'dreadful', 'atrocious', 'ghastly'],
  'test': ['trial', 'experiment', 'assessment', 'evaluation'],
  'text': ['writing', 'content', 'words', 'passage'],
  'theme': ['topic', 'subject', 'motif', 'idea'],
  'theory': ['idea', 'concept', 'hypothesis', 'framework'],
  'therefore': ['so', 'thus', 'as a result', 'consequently', 'hence'],
  'thick': ['dense', 'heavy', 'deep'],
  'thing': ['item', 'object', 'piece', 'stuff'],
  'think': ['believe', 'consider', 'reckon', 'feel', 'figure'],
  'thorough': ['comprehensive', 'complete', 'detailed', 'in-depth'],
  'though': ['although', 'even though', 'however'],
  'threat': ['danger', 'risk', 'menace', 'peril'],
  'tight': ['strict', 'close', 'limited', 'firm'],
  'time': ['period', 'moment', 'era', 'point'],
  'tiny': ['small', 'little', 'minuscule', 'microscopic'],
  'title': ['name', 'heading', 'label', 'designation'],
  'today': ['nowadays', 'currently', 'these days', 'in the present'],
  'together': ['jointly', 'collectively', 'as one', 'in combination'],
  'topic': ['subject', 'theme', 'issue', 'matter'],
  'total': ['complete', 'entire', 'overall', 'full'],
  'tough': ['hard', 'difficult', 'challenging', 'demanding'],
  'toward': ['towards', 'in the direction of', 'heading to'],
  'trace': ['track', 'follow', 'trail', 'find'],
  'track': ['follow', 'monitor', 'keep tabs on', 'trail'],
  'traditional': ['conventional', 'classic', 'established', 'old-school'],
  'transfer': ['move', 'shift', 'hand over', 'pass along'],
  'transform': ['change', 'convert', 'revolutionize', 'turn into'],
  'transition': ['shift', 'change', 'move', 'handover'],
  'translate': ['convert', 'render', 'put into', 'turn into'],
  'transport': ['carry', 'move', 'transit', 'ship'],
  'trap': ['catch', 'snare', 'ambush', 'pin down'],
  'treat': ['handle', 'deal with', 'approach', 'address'],
  'trend': ['pattern', 'direction', 'movement', 'wave'],
  'trial': ['test', 'experiment', 'attempt', 'run'],
  'trigger': ['spark', 'set off', 'activate', 'prompt'],
  'trouble': ['problem', 'difficulty', 'issue', 'headache'],
  'true': ['real', 'genuine', 'accurate', 'correct', 'factual'],
  'trust': ['believe in', 'rely on', 'have faith in', 'count on'],
  'truth': ['fact', 'reality', 'honest truth'],
  'turn': ['shift', 'change', 'flip', 'switch'],
  'typical': ['normal', 'standard', 'usual', 'average', 'ordinary'],
  // U
  'ultimate': ['final', 'supreme', 'absolute', 'highest'],
  'understand': ['comprehend', 'grasp', 'get', 'follow', 'wrap your head around'],
  'unite': ['join', 'combine', 'come together', 'band together'],
  'university': ['college', 'school', 'institution', 'academy'],
  'unlikely': ['improbable', 'doubtful', 'not likely', 'a long shot'],
  'unusual': ['uncommon', 'rare', 'strange', 'out of the ordinary'],
  'update': ['refresh', 'revise', 'bring up to date', 'modernize'],
  'upgrade': ['improve', 'enhance', 'elevate', 'step up'],
  'uphold': ['support', 'maintain', 'defend', 'back up'],
  'urgency': ['pressing need', 'importance', 'priority', 'rush'],
  'useful': ['helpful', 'practical', 'handy', 'valuable'],
  'usual': ['normal', 'typical', 'standard', 'routine', 'regular'],
  'utilize': ['use', 'employ', 'apply', 'put to work', 'leverage'],
  // V
  'valid': ['legitimate', 'sound', 'legit', 'proper'],
  'value': ['worth', 'importance', 'significance', 'merit'],
  'variable': ['factor', 'element', 'uncertainty', 'unknown'],
  'vast': ['huge', 'enormous', 'massive', 'expansive', 'immense'],
  'verify': ['confirm', 'validate', 'check', 'double-check'],
  'version': ['edition', 'variant', 'iteration', 'release'],
  'very': ['extremely', 'incredibly', 'really', 'super', 'quite'],
  'view': ['perspective', 'opinion', 'take', 'angle', 'standpoint'],
  'vital': ['crucial', 'essential', 'critical', 'key', 'must-have'],
  'voice': ['say', 'speak up', 'express', 'articulate'],
  'volume': ['amount', 'quantity', 'bulk', 'number'],
  // W
  'waste': ['squander', 'misuse', 'throw away', 'burn through'],
  'watch': ['observe', 'monitor', 'keep an eye on', 'pay attention to'],
  'weak': ['feeble', 'fragile', 'flimsy', 'lacking'],
  'wealth': ['riches', 'money', 'fortune', 'assets'],
  'weapon': ['tool', 'instrument', 'means', 'arm'],
  'weight': ['heaviness', 'mass', 'load', 'burden'],
  'whole': ['entire', 'complete', 'full', 'total'],
  'widespread': ['common', 'prevalent', 'extensive', 'rampant'],
  'willing': ['ready', 'open to', 'inclined', 'eager'],
  'wind': ['breeze', 'air', 'gust', 'draft'],
  'wise': ['smart', 'clever', 'sensible', 'judicious'],
  'wish': ['hope', 'want', 'desire', 'dream'],
  'within': ['inside', 'in', 'during'],
  'without': ['lacking', 'free of', 'devoid of'],
  'wonderful': ['great', 'amazing', 'fantastic', 'marvelous'],
  'word': ['term', 'expression', 'statement'],
  'work': ['job', 'task', 'labor', 'effort'],
  'world': ['globe', 'planet', 'earth', 'society'],
  'worry': ['concern', 'stress', 'anxiety', 'fret'],
  'worth': ['valuable', 'meaningful', 'important', 'of value'],
  'write': ['pen', 'draft', 'compose', 'put down'],
  'wrong': ['incorrect', 'mistaken', 'off', 'not right'],
  // Y
  'year': ['twelve months', 'calendar year', 'cycle'],
  'yield': ['produce', 'generate', 'return', 'output'],
  'young': ['early', 'new', 'fresh'],
};

// Safe synonyms only — these never change meaning or break grammar
// when swapped context-blindly. Curated subset ~100 words.
const SAFE_SYNONYMS: Record<string, string[]> = {
  'actually': ['really', 'honestly', 'truthfully', 'in fact'],
  'basically': ['essentially', 'pretty much', 'fundamentally', 'at its core'],
  'because': ['since', 'as', 'seeing as', 'given that'],
  'before': ['earlier', 'prior', 'leading up to', 'ahead of'],
  'begin': ['start', 'kick off', 'get going', 'launch'],
  'believe': ['think', 'feel', 'reckon', 'figure'],
  'big': ['large', 'huge', 'massive', 'major'],
  'change': ['shift', 'alter', 'modify', 'revamp'],
  'choose': ['pick', 'select', 'opt for', 'go with'],
  'clear': ['obvious', 'plain', 'apparent', 'straightforward'],
  'common': ['widespread', 'typical', 'standard', 'usual'],
  'create': ['make', 'build', 'craft', 'develop'],
  'deadline': ['cutoff', 'due date', 'time limit'],
  'decide': ['choose', 'settle on', 'make up your mind', 'resolve'],
  'different': ['distinct', 'various', 'diverse', 'unlike'],
  'difficult': ['hard', 'tough', 'challenging', 'tricky'],
  'end': ['finish', 'wrap up', 'close', 'conclude'],
  'enough': ['plenty', 'sufficient', 'adequate'],
  'especially': ['particularly', 'notably', 'specifically', 'above all'],
  'exactly': ['precisely', 'spot-on', 'specifically'],
  'fast': ['quick', 'rapid', 'swift', 'speedy'],
  'finally': ['at last', 'in the end', 'after all that'],
  'find': ['discover', 'come across', 'stumble upon', 'uncover'],
  'first': ['initially', 'to start', 'for starters', 'first off'],
  'focus': ['concentrate', 'zero in', 'hone in', 'center'],
  'follow': ['track', 'pursue', 'go after', 'trail'],
  'get': ['obtain', 'acquire', 'land', 'pick up'],
  'give': ['provide', 'supply', 'hand over', 'deliver'],
  'good': ['solid', 'great', 'strong', 'quality'],
  'grow': ['expand', 'increase', 'develop', 'build up'],
  'handle': ['deal with', 'manage', 'tackle', 'take care of'],
  'happen': ['occur', 'take place', 'come about', 'go down'],
  'help': ['assist', 'support', 'aid', 'lend a hand'],
  'huge': ['massive', 'enormous', 'gigantic', 'immense'],
  'idea': ['concept', 'thought', 'notion', 'plan'],
  'important': ['crucial', 'key', 'vital', 'significant'],
  'improve': ['enhance', 'boost', 'upgrade', 'better'],
  'include': ['feature', 'incorporate', 'cover', 'involve'],
  'interesting': ['fascinating', 'intriguing', 'compelling', 'thought-provoking'],
  'keep': ['maintain', 'hold on to', 'retain', 'preserve'],
  'know': ['understand', 'realize', 'be aware'],
  'large': ['big', 'huge', 'substantial', 'sizeable'],
  'learn': ['find out', 'pick up', 'figure out', 'discover'],
  'look': ['appear', 'seem', 'come across as'],
  'main': ['primary', 'chief', 'principal', 'key'],
  'make': ['create', 'build', 'craft', 'produce'],
  'many': ['a lot of', 'tons of', 'quite a few', 'numerous'],
  'method': ['approach', 'technique', 'way', 'strategy'],
  'necessary': ['required', 'essential', 'needed', 'must-have'],
  'new': ['fresh', 'novel', 'recent', 'latest'],
  'often': ['frequently', 'regularly', 'commonly', 'a lot'],
  'old': ['previous', 'former', 'past', 'earlier'],
  'part': ['piece', 'section', 'portion', 'component'],
  'place': ['spot', 'location', 'area', 'site'],
  'plan': ['strategy', 'scheme', 'blueprint', 'proposal'],
  'point': ['purpose', 'objective', 'goal', 'message'],
  'problem': ['issue', 'challenge', 'difficulty', 'headache'],
  'quick': ['fast', 'rapid', 'swift', 'speedy'],
  'really': ['truly', 'genuinely', 'actually', 'honestly'],
  'reason': ['cause', 'motive', 'basis', 'rationale'],
  'result': ['outcome', 'consequence', 'effect', 'end product'],
  'right': ['correct', 'proper', 'appropriate', 'suitable'],
  'see': ['notice', 'observe', 'spot', 'catch'],
  'seem': ['appear', 'look like', 'come across as'],
  'show': ['reveal', 'display', 'present', 'demonstrate'],
  'simple': ['easy', 'straightforward', 'basic', 'uncomplicated'],
  'small': ['tiny', 'little', 'modest', 'minor'],
  'start': ['begin', 'kick off', 'launch', 'get going'],
  'still': ['yet', 'even so', 'nevertheless'],
  'stop': ['halt', 'cease', 'end', 'quit'],
  'think': ['believe', 'consider', 'reckon', 'feel'],
  'try': ['attempt', 'make an effort', 'give it a shot'],
  'turn': ['shift', 'change', 'flip', 'switch'],
  'use': ['employ', 'apply', 'put to work', 'utilize'],
  'very': ['extremely', 'incredibly', 'super', 'quite'],
  'want': ['need', 'desire', 'wish', 'aim for'],
  'way': ['method', 'approach', 'manner', 'strategy'],
  'work': ['job', 'task', 'labor', 'effort'],
  'worth': ['valuable', 'meaningful', 'of value'],
};

// Helper to get a random synonym for a word
export function getRandomSynonym(word: string): string | null {
  const lower = word.toLowerCase().replace(/[^a-z]/g, '');
  const candidates = SYNONYMS[lower];
  if (!candidates || candidates.length === 0) return null;
  return candidates[Math.floor(Math.random() * candidates.length)];
}

// Safe synonym lookup — only from the curated safe list
export function getRandomSafeSynonym(word: string): string | null {
  const lower = word.toLowerCase().replace(/[^a-z]/g, '');
  const candidates = SAFE_SYNONYMS[lower];
  if (!candidates || candidates.length === 0) return null;
  return candidates[Math.floor(Math.random() * candidates.length)];
}
