name: Quality

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v24
        with:
          globs: |
            **/*.md
            !node_modules/**
